name: hello-world
on:
  push:
    branches:
       -master 
       -production
jobs: 
   my-jobs:
     runs-on:  windows-latest
       steps:
            name: mystep
            run: date
     

     
   
